In [1]:
#pip install Bio

In [2]:
from Bio import SeqIO
import numpy as np

In [3]:
def simple_difference_distance(s1, s2):
    i = len(s1)
    j = 0
    distance = 0

    diff = np.array(s1) - np.array(s2)
    distance = sum([abs(x) for x in diff])
    return distance

In [4]:
def five_two_adic_distance(s1, s2):
    distance = 0
    for i in range(len(s1)):
        if int(s1[i]/100) != int(s2[i]/100):
            distance += 1
            
        elif int(s1[i]/10) != int(s2[i]/10):
            distance += 1/5
            
        elif s1[i] % 10 != s2[i] % 10:
            if abs(s1[i] % 10 - s2[i] % 10) == 2:
                distance += 1/2*1/25
            else:
                distance += 1*1/25
    return distance
            
        

In [5]:
def five_adic_coding(s):
    seq = []
    num = ''
    i = 0
    for c in s:
        if c == 'C':
            num += '1'
        elif c == 'A':
            num += '2'
        elif c == 'T':
            num += '3'
        else:
            num += '4'
        i += 1
        if i == 3:
            i = 0
            seq.append(int(num))
            num = ''

        if len(seq) == 3: # should be 40
            break
    return seq



In [6]:
def read_data(filePath):
    with open(filePath) as file:
        fasta_sequences_sars1 = SeqIO.parse(file,'fasta')
        data = []
        for fasta in fasta_sequences_sars1:
            seq = five_adic_coding(fasta.seq)
            data.append(seq)
    return data

In [7]:
X = read_data("../data/sars1.fasta")
y = ['sars1' for i in range(len(X))]
X2 = read_data("../data/mers.fasta")

for x in X2:
    X.append(x)
    y.append('mers')

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
len(y)

7054

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, stratify=y)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
model = KNeighborsClassifier(n_neighbors=3, algorithm='ball_tree', metric=simple_difference_distance)

In [13]:
model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree',
                     metric=<function simple_difference_distance at 0x7fb6e23a5820>,
                     n_neighbors=3)

In [14]:
y_pred = model.predict(X_test)

In [15]:
y_test.count('mers')

2291

In [16]:
y_test.count('sars1')

37

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [18]:
accuracy_score(y_test, y_pred)

0.9961340206185567

In [19]:
confusion_matrix(y_test, y_pred)

array([[2282,    9],
       [   0,   37]])

In [20]:
y_pred_train = model.predict(X_train)

In [21]:
accuracy_score(y_train, y_pred_train)

0.9995768091409225

In [22]:
confusion_matrix(y_train, y_pred_train)

array([[4650,    2],
       [   0,   74]])

In [23]:
model2 = KNeighborsClassifier(n_neighbors=3, algorithm='ball_tree', metric=five_two_adic_distance)

In [24]:
model2.fit(X_train, y_train)

KNeighborsClassifier(algorithm='ball_tree',
                     metric=<function five_two_adic_distance at 0x7fb6e23a6040>,
                     n_neighbors=3)

In [25]:
y_pred = model2.predict(X_test)

In [26]:
accuracy_score(y_test, y_pred)

0.9969931271477663

In [27]:
confusion_matrix(y_test, y_pred)

array([[2284,    7],
       [   0,   37]])

In [28]:
y_pred_train = model2.predict(X_train)

In [29]:
accuracy_score(y_train, y_pred_train)

0.9991536182818451

In [30]:
confusion_matrix(y_train, y_pred_train)

array([[4648,    4],
       [   0,   74]])

In [33]:
# TO DO uraditi sve importovanjem iz 