In [1]:
from Bio import SeqIO
import numpy as np
from typing import List
import importlib
import fileDistanceProcessing as fdp
import importlib
importlib.reload(fdp) 

<module 'fileDistanceProcessing' from '/home/marko/Desktop/ip2/ip2_projekat/source/fileDistanceProcessing.py'>

In [2]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
X_train, X_test, y_train, y_test = fdp.train_test_virus()

In [4]:
def get_gram(X1, X2, kernel):
    return np.array([[kernel(X1[i], X2[j]) for j in range(len(X2))] for i in range(len(X1))])

In [5]:
distances = fdp.deserialize_and_decompress_distance_matrix("../data/full_distances_matrix.7z")

# metrika zasnovana samo na 5-adic distanci
# instant racunanje iz matrice
def five_adic_distance_from_matrix(x, y):

    i = int(x[-1]) #indeks je na poslednjem mestu u listi
    j = int(y[-1])

    # matrica je u obliku trougla bez dijagonale originalne matrice
    first = min(i, j)
    second = max(i, j) - (first + 1) # veci indeks smanji za broj instanci u redu matrice do dijagonale 

    return 0 if i == j else -distances[first][second] #udaljenost x od y

In [6]:
clf1 = svm.SVC(kernel = "precomputed")
clf1.fit(get_gram(X_train, X_train, five_adic_distance_from_matrix), y_train)

/home/marko/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='precomputed')

In [7]:
y_pred = clf1.predict(get_gram(X_test, X_train, five_adic_distance_from_matrix))

In [8]:
print(f'Accuracy on Custom Kernel: {accuracy_score(y_test, y_pred)}')

Accuracy on Custom Kernel: 0.9993114528345192


In [9]:
labels = y_test["Virus"].unique()
confusion_matrix(y_test, y_pred, labels=labels)

array([[3740,    0,    0],
       [   1,  610,    0],
       [   2,    0,    4]])

In [10]:
X_train, X_test, y_train, y_test = fdp.train_test_protein()

In [11]:
clf1.fit(get_gram(X_train, X_train, five_adic_distance_from_matrix), y_train)

/home/marko/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='precomputed')

In [12]:
y_pred = clf1.predict(get_gram(X_test, X_train, five_adic_distance_from_matrix))

In [13]:
print(f'Accuracy on Custom Kernel: {accuracy_score(y_test, y_pred)}')

Accuracy on Custom Kernel: 0.9986229056690383


In [14]:
confusion_matrix(y_test, y_pred)

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           1,    0,    0,    0,    0,    0,    0],
       [   0, 1371,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 1899,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    2,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,   32,    0,    2,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,   73,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    1,    0,   21,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,   41,    1,    0,    0,
           0,    0,    0,    0,    0,    0,    0],


In [15]:
X_train, X_test, y_train, y_test = fdp.train_test_sars2()

In [16]:
clf1.fit(get_gram(X_train, X_train, five_adic_distance_from_matrix), y_train)

/home/marko/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='precomputed')

In [17]:
y_pred = clf1.predict(get_gram(X_test, X_train, five_adic_distance_from_matrix))

In [18]:
print(f'Accuracy on Custom Kernel: {accuracy_score(y_test, y_pred)}')

Accuracy on Custom Kernel: 0.9713903743315508


In [19]:
confusion_matrix(y_test, y_pred)

array([[484,   1,   1,   1,   0,   0,   0,   0,   2,   0,   0,   0,   6],
       [  0, 182,   3,   0,   0,   0,   3,   0,   3,   0,   2,   0,   0],
       [  2,   1, 482,   2,   0,   2,   0,   6,   0,   0,   0,   0,   0],
       [  0,   2,   4, 487,   0,   0,   1,   0,   0,   0,   0,   0,   1],
       [  0,   0,   1,   1, 197,   1,   1,   0,   0,   0,   0,   0,   6],
       [  3,   6,   0,   2,   0, 478,   3,   0,   3,   0,   0,   0,   0],
       [  0,   0,   0,   1,   0,   0, 493,   0,   0,   0,   1,   0,   0],
       [  2,   0,   3,   0,   0,   0,   0,  47,   0,   0,   0,   0,   0],
       [  0,   0,   3,   2,   0,   0,   0,   0, 127,   0,   0,   0,   3],
       [  0,   2,   0,   2,   0,   0,   1,   0,   0,  17,   0,   0,   0],
       [  3,   0,   3,   1,   0,   0,   4,   0,   0,   0, 482,   0,   2],
       [  0,   0,   1,   0,   0,   1,   0,   0,   0,   0,   0,   5,   0],
       [  0,   0,   0,   0,   0,   0,   1,   0,   1,   0,   0,   0, 152]])